# Generated by Django 3.1.3 on 2020-11-29 03:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_auto_20201127_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='total_votes',
            field=models.ManyToManyField(related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
